# Generated by Django 4.0 on 2021-12-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='average_rating',
            field=models.IntegerField(default=4.5),
        ),
        migrations.AddField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='tot_hours_of_service',
            field=models.IntegerField(default=10),
        ),
    ]
