# Generated by Django 4.0 on 2021-12-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_average_rating_profile_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='average_rating',
            field=models.IntegerField(default=5),
        ),
    ]
