# Generated by Django 4.0 on 2022-01-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tot_hours_of_service',
            field=models.IntegerField(default=5),
        ),
    ]
