version: "3.9"

services:
  web:
    container_name: swe573-time_sharing
    build: .
    restart: always
    env_file: ./time_sharing_v3/.env
    volumes:
      - .:/SWE573_Project
      - static_volume:/SWE573_Project/static
    ports:
      - "80:8000"
    depends_on:
      - db

  db:
    container_name: time_sharing_db
    env_file: ./time_sharing_v3/.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  static_volume:
