version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py makemigrations && python manage.py migrate &&python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=db_v1
      - POSTGRES_USER=alperturgal
      - POSTGRES_PASSWORD=postgres


    depends_on:
      - db