version: "3.9"

services:
  web:
    container_name: swe573
    build: .
    command: python manage.py makemigrations && python manage.py makemigrations && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "10555:8000"

    depends_on:
      - db
  db:
    image: postgres
    container_name: swe573db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_v1
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
