# Generated by Django 4.0 on 2021-12-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrequests',
            name='message',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
