# Generated by Django 4.0 on 2021-12-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_serviceoffer_offer_creator'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('offer_requests', '0003_alter_offerrequests_related_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrequests',
            name='related_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.serviceoffer'),
        ),
        migrations.AlterField(
            model_name='offerrequests',
            name='request_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
