# Generated by Django 4.0 on 2021-12-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_serviceoffer_offer_creator'),
        ('offer_requests', '0005_remove_offerrequests_related_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrequests',
            name='related_offer',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='offers.serviceoffer'),
            preserve_default=False,
        ),
    ]
