# Generated by Django 4.0 on 2021-12-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_requests', '0006_offerrequests_related_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrequests',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
