# Generated by Django 4.0 on 2021-12-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_requests', '0007_offerrequests_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerrequests',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='offerrequests',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
