# Generated by Django 4.0 on 2021-12-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_requests', '0008_remove_offerrequests_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrequests',
            name='response_message',
            field=models.TextField(default='Kabul ettiğiniz için teşekkürler, görüşmek üzere..'),
        ),
        migrations.AlterField(
            model_name='offerrequests',
            name='message',
            field=models.TextField(default='Teklifinizle ilgileniyorum, teşekkürler..'),
        ),
    ]
