# Generated by Django 4.0 on 2021-12-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_requests', '0009_offerrequests_response_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrequests',
            name='offer_creator_id',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
