# Generated by Django 4.0 on 2021-12-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_requests', '0010_offerrequests_offer_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrequests',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
