# Generated by Django 4.0 on 2022-01-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_alter_serviceoffer_service_comment'),
        ('offer_requests', '0012_alter_offerrequests_related_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerrequests',
            name='related_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='offers.serviceoffer'),
        ),
    ]
