# Generated by Django 4.0 on 2022-01-03 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offer_requests', '0014_remove_offerrequests_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrequests',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
