# Generated by Django 4.0 on 2022-01-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_requests', '0015_offerrequests_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerrequests',
            name='is_offer_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
