# Generated by Django 4.0 on 2021-12-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(max_length=200, verbose_name='Service Category')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_subcategory', models.CharField(max_length=200, verbose_name='Service Subcategory')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
                ('service_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicesubcategory')),
            ],
        ),
    ]
