# Generated by Django 4.0 on 2021-12-13 21:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.TextField(max_length=200, verbose_name='Title')),
                ('service_name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('service_description', models.TextField(max_length=200, verbose_name='Description')),
                ('service_date', models.DateField(verbose_name='Date of Delivery')),
                ('service_start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Starting')),
                ('service_duration', models.IntegerField(verbose_name='Duration (Hours)')),
                ('service_city', models.CharField(max_length=200, verbose_name='Your City')),
                ('service_district', models.CharField(max_length=200, verbose_name='Your District')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory')),
                ('service_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicesubcategory')),
            ],
        ),
    ]
