# Generated by Django 4.0 on 2021-12-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='offer_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
