# Generated by Django 4.0 on 2021-12-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('offers', '0003_alter_serviceoffer_offer_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffer',
            name='offer_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
