# Generated by Django 4.0 on 2021-12-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_serviceoffer_offer_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
    ]
