# Generated by Django 4.0 on 2021-12-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_serviceoffer_request_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
