# Generated by Django 4.0 on 2022-01-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_serviceoffer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='service_comment',
            field=models.CharField(default='lorem ipsum', max_length=200, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='service_rating',
            field=models.IntegerField(default=5),
        ),
    ]
