# Generated by Django 4.0 on 2022-01-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_serviceoffer_service_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffer',
            name='service_comment',
            field=models.CharField(default='Yorum yazabilirsiniz..', max_length=200, verbose_name='Yorumunuz'),
        ),
    ]
