# Generated by Django 4.0 on 2022-01-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_alter_serviceoffer_service_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='is_request_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='is_service_provider_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='is_service_taker_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
