# Generated by Django 4.0 on 2022-01-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_serviceoffer_is_request_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='service_spot',
            field=models.CharField(default='Maçka Parkı', max_length=200, verbose_name='Your City'),
        ),
    ]
