# Generated by Django 4.0 on 2022-01-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_serviceoffer_service_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffer',
            name='service_spot',
            field=models.CharField(default='Maçka Parkı', max_length=200, verbose_name='Lokasyon'),
        ),
    ]
