# Generated by Django 4.0 on 2022-01-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_alter_serviceoffer_service_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='accepted_request',
            field=models.IntegerField(default=0),
        ),
    ]
