# Generated by Django 4.0 on 2022-01-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_serviceoffer_accepted_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceoffer',
            old_name='accepted_request',
            new_name='accepted_request_id',
        ),
    ]
