# Generated by Django 4.0 on 2022-01-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_rename_accepted_request_serviceoffer_accepted_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffer',
            name='accepted_request_id',
        ),
    ]
