# Generated by Django 4.0 on 2022-01-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_remove_serviceoffer_accepted_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='accepted_request_id',
            field=models.IntegerField(default=0),
        ),
    ]
