# Generated by Django 4.0 on 2022-01-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_serviceoffer_accepted_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='service_new_duration',
            field=models.IntegerField(default=0, verbose_name='Duration (Hours)'),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
