# Generated by Django 4.0 on 2022-01-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_serviceoffer_service_new_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='is_service_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
