# Generated by Django 4.0 on 2022-01-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_serviceoffer_is_service_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffer',
            name='service_spot',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
    ]
